#include <stdafx.hpp>
#include <render/menu/localization.hpp>

namespace render::localization
{

namespace
{

std::atomic<id> g_current{id::en};

const std::unordered_map<std::string_view, const char *> &russian()
{
    static const std::unordered_map<std::string_view, const char *> table{
        // --- navigation -------------------------------------------------
        {"Aimbot", "Аим"},
        {"Triggerbot", "Триггер"},
        {"Visuals", "Визуалы"},
        {"Misc", "Разное"},

        // --- weapon group tabs ------------------------------------------
        {"Global", "Общие"},
        {"Pistol", "Пистолеты"},
        {"SMG", "ПП"},
        {"Rifle", "Винтовки"},
        {"Shotgun", "Дробовики"},
        {"Sniper", "Снайперки"},
        {"Heavy", "Пулемёты"},

        // --- combat cards -----------------------------------------------
        {"TARGETING", "НАВЕДЕНИЕ"},
        {"PENETRATION", "ПРОБИТИЕ"},
        {"VISUALIZATION", "ОТОБРАЖЕНИЕ"},
        {"TRIGGERBOT CORE", "ТРИГГЕР"},
        {"ADVANCED MODE", "РАСШИРЕННЫЙ"},
        // This card holds Auto Stop / Early Auto Stop -- it is about stopping
        // before the shot, not about the movement features in Misc.
        {"MOVEMENT", "АВТОСТОП"},
        {"OVERRIDE SETTINGS", "ПЕРЕОПРЕДЕЛЕНИЕ"},

        // --- combat rows ------------------------------------------------
        {"Master Switch", "Включить"},
        {"Activation", "Активация"},
        {"Activation Mode", "Режим активации"},
        {"Hold", "По удержанию"},
        {"Always On", "Всегда"},
        {"Toggle", "Переключение"},
        {"Damage Override", "Переопределение урона"},
        {"Override Damage", "Альтернативный урон"},
        {"Checks", "Условия"},
        {"Jump", "Прыжок"},
        {"Flash", "Ослепление"},
        {"Airborne", "В воздухе"},
        {"Flashed", "Ослепление"},
        {"Threshold", "Порог"},
        {"Smoke", "Дым"},
        {"Walls", "Стены"},
        {"Block", "Запрет"},
        {"Penetration", "Пробитие"},
        {"Ignore", "Игнорировать"},
        {"Trigger Key", "Бинд"},
        {"FOV", "FOV"},
        {"FOV Profile", "Профиль FOV"},
        {"Radius", "Радиус"},
        {"Max Radius", "Макс. радиус"},
        {"Min Radius", "Мин. радиус"},
        {"Full Size At", "Полный размер до"},
        {"Min Size At", "Мин. размер после"},
        {"Advanced", "Дополнительно"},
        {"Fixed", "Фиксированный"},
        {"Distance", "По дистанции"},
        {"Target", "На цели"},
        {"Near Distance", "Ближняя дистанция"},
        {"Near FOV", "Ближний FOV"},
        {"Far Distance", "Дальняя дистанция"},
        {"Far FOV", "Дальний FOV"},
        {"Acquisition Area", "Область захвата"},
        {"Target Point", "Точка наведения"},
        {"Show FOV", "Показывать FOV"},
        {"Visualization", "Визуализация"},
        {"Smoothing", "Сглаживание"},
        {"Humanize", "Хуманизация"},
        {"Humanizer Tuning", "Тонкая настройка"},
        {"Humanizer Profile", "Профиль хуманизации"},
        {"Motion", "Движение"},
        {"Behavior", "Поведение"},
        {"Gravity", "Притяжение"},
        {"Wind", "Отклонение"},
        {"Max Step", "Максимальный шаг"},
        {"Damping", "Затухание"},
        {"Reaction Min", "Мин. реакция"},
        {"Reaction Max", "Макс. реакция"},
        {"Curve", "Кривизна"},
        {"Overshoot Chance", "Шанс перелёта"},
        {"Overshoot Amount", "Сила перелёта"},
        {"Jitter", "Микродрожание"},
        {"Deadzone", "Мёртвая зона"},
        {"Hitboxes", "Хитбоксы"},
        {"Multi-Point", "Мультипоинт"},
        {"Cap Points", "Торцевые точки"},
        {"Side Points", "Боковые точки"},
        {"Head Scale", "Масштаб головы"},
        {"Body Scale", "Масштаб тела"},
        {"Limbs Scale", "Масштаб конечностей"},
        {"Prediction", "Предикт"},
        {"Max Horizon", "Горизонт предикта"},
        {"Acceleration", "Учитывать ускорение"},
        {"RCS", "Контроль отдачи"},
        {"Start Bullet", "Начальная пуля"},
        {"Pitch Strength", "Сила по вертикали"},
        {"Yaw Strength", "Сила по горизонтали"},
        {"Humanization", "Хуманизация"},
        {"Response", "Отклик"},
        {"Gain Randomness", "Разброс силы"},
        {"Drift", "Дрейф"},
        {"Correction Time", "Время коррекции"},
        {"Smoothness", "Плавность"},
        {"Strength Variation", "Вариация силы"},
        {"Path Drift", "Дрейф траектории"},
        {"Wall Policy", "Прострелы"},
        {"Only Visible", "Только видимые"},
        {"Shot Timing", "Тайминг выстрела"},
        {"Randomize", "Рандомизация"},
        {"Outlier Chance", "Шанс выброса"},
        {"Outlier Delay", "Задержка выброса"},
        {"Lethal Only", "Только смертельный урон"},
        {"R8 Readiness", "Готовность R8"},
        {"Release Margin", "Запас отпускания"},
        {"Key", "Бинд"},
        {"Visible Only", "Только по видимым"},
        {"Predictive", "Предикт"},
        {"Recoil Sync", "Контроль отдачи"},
        {"Auto Wall", "Autowall"},
        {"Min Damage", "Мин. урон"},
        {"Draw FOV Circle", "Рисовать FOV"},
        {"Mode", "Режим"},
        {"Interface Colors", "Цвета интерфейса"},
        {"Typography", "Текст"},
        {"Primary Text", "Основной текст"},
        {"Muted Text", "Вторичный текст"},
        {"Surfaces", "Поверхности"},
        {"Menu Background", "Фон меню"},
        {"Controls", "Элементы управления"},
        {"Containers", "Контейнеры"},
        {"Popups", "Всплывающие окна"},
        {"Interaction", "Взаимодействие"},
        {"Accent", "Акцент"},
        {"Hover", "Наведение"},
        {"Borders", "Границы"},
        {"Seed Type", "Сид"},
        {"Hitchance", "Шанс попасть"},
        {"Delay (ms)", "Задержка (мс)"},
        {"Reaction Time (ms)", "Время реакции (мс)"},
        {"Auto Stop", "Auto Stop"},
        {"Early Auto Stop", "Early Auto Stop"},
        {"Delay Before", "Задержка до"},
        {"Delay After", "Задержка после"},
        {"Randomize (+-)", "Рандом (±)"},
        {"Inherit Global Settings", "Как в общих"},

        // --- shared option values ---------------------------------------
        {"Advanced", "Расширенный"},
        {"None", "Нет"},
        {"All", "Все"},
        {"Restricted", "Ограниченный"},
        {"Unrestricted", "Свободный"},
        {"Head", "Голова"},
        {"Body", "Тело"},
        {"Arms", "Руки"},
        {"Legs", "Ноги"},

        // --- visuals tabs -----------------------------------------------
        {"Players", "Игроки"},
        {"Items", "Дроп"},
        {"Projectiles", "Гранаты"},
        {"Bomb", "Бомба"},
        {"Radar", "Радар"},
        {"World", "Мир"},
        {"Crosshair", "Прицел"},

        // --- expanded radar / crosshair ---------------------------------
        {"Player Names", "Имена игроков"},
        {"Player Health", "Здоровье игроков"},
        {"Player Armor", "Броня игроков"},
        {"Player Weapon", "Оружие игроков"},
        {"Grenade Markers", "Маркеры гранат"},
        {"Grenade Trajectories", "Траектории гранат"},
        {"Grenade Zones", "Зоны гранат"},
        {"Information Scale", "Масштаб информации"},
        {"Overlay Enemy Markers", "Маркеры противников"},
        {"Enemy Marker", "Маркер противника"},
        {"View Direction", "Направление взгляда"},
        {"Status Text", "Текст состояния"},
        {"Marker Scale", "Масштаб маркера"},
        {"Text Outline", "Обводка текста"},
        {"HE Color", "Цвет HE"},
        {"Flash Color", "Цвет световой"},
        {"Smoke Color", "Цвет дыма"},
        {"Molotov Color", "Цвет огня"},
        {"Decoy Color", "Цвет ложной"},
        {"Line Thickness", "Толщина линии"},
        {"End Point Size", "Размер конечной точки"},
        {"Fill Opacity", "Прозрачность заливки"},
        {"Outline Opacity", "Прозрачность контура"},
        {"In-Game Avatars", "Внутриигровые аватары"},
        {"Copy Game Crosshair", "Копировать игровой прицел"},
        {"Outline Color", "Цвет обводки"},
        {"Outline Thickness", "Толщина обводки"},

        // --- player esp -------------------------------------------------
        {"MASTER", "ОСНОВНОЕ"},
        {"BOUNDING BOX", "БОКС"},
        {"DETAILS", "ИНФА"},
        {"SKELETON & HITBOXES", "СКЕЛЕТ И ХИТБОКСЫ"},
        {"Enable Player ESP", "Включить ESP"},
        {"Legit Sync", "Легитная синхронизация"},
        {"Spectator Sync", "Синхронизация со зрителями"},
        {"Direct Visibility", "Прямая видимость"},
        {"Radar Spotted", "Обнаружение радаром"},
        {"Audible Sounds", "Слышимые звуки"},
        {"Radar Hold", "Время радара"},
        {"Sound Hold", "Время звука"},
        {"Hearing Distance", "Дистанция слышимости"},
        {"Pulse Minimum", "Минимум пульсации"},
        {"Pulse Maximum", "Максимум пульсации"},
        {"Pulse Period", "Период пульсации"},
        {"Show Box", "Бокс"},
        {"Style", "Стиль"},
        {"Full", "Полный"},
        {"Cornered", "Углы"},
        {"Corner Length", "Длина углов"},
        {"Background Fill", "Заливка"},
        {"Box Visible Color", "Бокс: видимые"},
        {"Box Occluded Color", "Бокс: за стеной"},
        {"Fill Visible Color", "Заливка: видимые"},
        {"Fill Occluded Color", "Заливка: за стеной"},
        {"Show Name", "Ник"},
        {"Show Weapon", "Оружие"},
        {"Ammo Indicator", "Индикатор патронов"},
        {"Exact Ammo Count", "Точное число патронов"},
        {"Empty Color", "Цвет пустой части"},
        {"Bomb Damage", "Урон от бомбы"},
        {"Health Bar", "Бар ХП"},
        {"Ammo Bar", "Бар патронов"},
        {"Info Flags", "Флаги"},
        {"Chams", "Чамсы"},
        {"Antialiasing", "Сглаживание"},
        {"Model Glow", "Свечение модели"},
        {"Glow Color", "Цвет свечения"},
        {"Glow Radius", "Радиус свечения"},
        {"Glow Strength", "Яркость свечения"},
        {"Glow Layers", "Слои свечения"},
        {"Death Shatter", "Распад при смерти"},
        {"On Hit Chams", "Чамсы при попадании"},
        {"Kill Particles", "Частицы смерти"},
        {"Particle Color", "Цвет частиц"},
        {"Particle Duration", "Время частиц"},
        {"Particle Size", "Размер частиц"},
        {"Particle Count", "Количество частиц"},
        {"On Shot Chams", "Чамсы при выстреле"},
        {"Ghost Duration", "Время слепка"},
        {"Ghost Appearance", "Вид слепка"},
        {"Occlusion", "Перекрытия"},
        {"Dynamic Doors", "Динамические двери"},
        {"Smoke Occlusion", "Перекрытие дымом"},
        {"Chams Visible", "Чамсы: видимые"},
        {"Chams Occluded", "Чамсы: за стеной"},
        {"Show Skeleton", "Скелет"},
        {"Show Head Circle", "Круг на голове"},
        {"Show View Line", "Линия взгляда"},
        {"Offscreen Arrows", "Стрелки за экраном"},
        {"Arrow Color", "Цвет стрелки"},
        {"Arrow Size", "Размер стрелки"},
        {"Arrow Radius", "Радиус стрелок"},
        {"Bloom Speed", "Скорость свечения"},
        {"Minimum Glow", "Минимальное свечение"},
        {"Maximum Glow", "Максимальное свечение"},
        {"Threat Hitboxes", "Хитбоксы"},
        {"SOUND ESP", "ЗВУКИ"},
        {"Sound ESP", "Звуки"},
        {"Enable Sound ESP", "Показывать звуки"},
        {"Ring Color", "Цвет круга"},
        {"Local Sync", "Только слышимые"},
        {"Duration", "Длительность"},
        {"Ring Radius", "Радиус круга"},
        {"Audible Distance", "Дальность слуха"},
        {"Head Hitbox Color", "Цвет: голова"},
        {"Body Hitbox Color", "Цвет: тело"},
        {"Fill Alpha", "Прозрачность"},

        // --- chams materials --------------------------------------------
        {"Material", "Материал"},
        {"Color", "Цвет"},
        {"Wireframe", "Сетка"},
        {"Roughness", "Шероховатость"},
        {"Metalness", "Металличность"},
        {"Exponent", "Степень"},
        {"Falloff", "Спад"},
        {"Fresnel Filling", "Заливка Френеля"},
        {"Strength", "Интенсивность"},
        {"Speed", "Скорость"},
        {"Tint", "Оттенок"},
        {"Solid", "Сплошной"},
        {"Shaded", "С затенением"},
        {"Glow", "Свечение"},

        {"Glow Outline", "Контур"},
        {"Iridescent", "Перелив"},
        {"Water Flow", "Вода"},
        {"Glossy", "Глянец"},

        // --- item esp ---------------------------------------------------
        {"SETTINGS", "НАСТРОЙКИ"},
        {"FILTERS", "ФИЛЬТРЫ"},
        {"Enable Item ESP", "Включить ESP дропа"},
        {"Max Distance", "Дистанция"},
        {"Show Icon", "Иконка"},
        {"Show Item Name", "Название"},
        {"Rifles", "Винтовки"},
        {"SMGs", "ПП"},
        {"Snipers", "Снайперки"},
        {"Pistols", "Пистолеты"},
        {"Grenades", "Гранаты"},
        {"Utility", "Утилити"},

        // --- projectile esp ---------------------------------------------
        {"VISUAL ELEMENTS", "ЭЛЕМЕНТЫ"},
        {"COLORS", "ЦВЕТА"},
        {"Enable Projectiles", "Включить ESP гранат"},
        {"Display Mode", "Режим отображения"},
        {"Indicator", "Индикатор"},
        {"Text Only", "Только текст"},
        {"Show Text", "Показывать текст"},
        {"Effect Timer", "Таймер эффекта"},
        {"Effect Timer Ring", "Кольцо таймера"},
        {"Inferno Bounds", "Границы молика"},
        {"INDICATOR", "ИНДИКАТОР"},
        {"Timer Full", "Таймер: полный"},
        {"Timer Low", "Таймер: конец"},
        {"Indicator Background", "Фон индикатора"},
        {"INFERNO GRADIENT", "ГРАДИЕНТ INFERNO"},
        {"Gradient Width", "Ширина градиента"},
        {"Gradient Opacity", "Яркость градиента"},
        {"HE Grenade", "Хешка"},
        {"Flashbang", "Флешка"},
        {"Smoke", "Смок"},
        {"Molotov", "Молик"},
        {"Decoy", "Декой"},

        // --- bomb esp ---------------------------------------------------
        {"STATES", "СОСТОЯНИЯ"},
        {"SAFE ZONE (BAKED)", "БЕЗОПАСНАЯ ЗОНА"},
        {"Enable Bomb ESP", "Включить ESP бомбы"},
        {"Show Carrier", "Носитель бомбы"},
        {"Show Planted", "Установленная"},
        {"Planted Color", "Цвет установленной"},
        {"Defusing Color", "Цвет дефуза"},
        {"Panel Background", "Фон панели"},
        {"World Timer Ring", "Кольцо таймера в мире"},
        {"World Timer", "Таймер в мире"},
        {"Bomb Info Panel", "Панель информации о бомбе"},
        {"Timer Color", "Цвет таймера"},
        {"Safe Zone Contour", "Контур зоны"},
        {"Zone Color", "Цвет зоны"},
        {"Gradient Bands", "Изолинии"},
        {"Band Step", "Шаг изолиний"},

        // --- radar / world ----------------------------------------------
        {"RADAR OVERLAY", "РАДАР"},
        {"Overlay Enemy Markers", "Метки врагов"},
        {"NO FLASH (WIREFRAME)", "NO FLASH (СЕТКА)"},
        {"Enable Visual No Flash", "Включить No Flash"},
        {"Render Distance", "Дистанция"},
        {"Dimming Overlay Color", "Цвет затемнения"},
        {"Wireframe Color", "Цвет сетки"},
        {"NO SMOKE (WIREFRAME)", "NO SMOKE (СЕТКА)"},
        {"Enable Visual No Smoke", "Включить No Smoke"},
        {"Smoke Wireframe Color", "Цвет сетки в дыму"},

        // --- crosshair --------------------------------------------------
        {"CROSSHAIR SETTINGS", "ПРИЦЕЛ"},
        {"Enable Crosshair", "Включить прицел"},
        {"Weapon Sync", "Синхронизация"},
        {"Draw Dot", "Точка"},
        {"Draw Lines", "Линии"},
        {"T-Style", "T-образный"},
        {"Length", "Длина"},
        {"Gap", "Зазор"},
        {"Thickness", "Толщина"},
        {"Draw Outline", "Обводка"},
        {"Primary Color", "Цвет"},
        {"Penetration Indicator", "Индикатор пенетрации"},
        {"Can Penetrate", "Пробьёт"},
        {"Cannot Penetrate", "Не пробьёт"},

        // --- misc tabs --------------------------------------------------
        {"General", "Общее"},
        {"Movement", "Мувмент"},
        {"Effects", "Эффекты"},
        {"Overlay", "Оверлей"},
        {"Lua API", "Lua API"},
        {"Configs", "Конфиги"},
        {"LUA RUNTIME", "LUA RUNTIME"},
        {"SCRIPTS", "СКРИПТЫ"},
        {"Enable Lua API", "Включить Lua API"},
        {"Script Directory", "Директория скриптов"},
        {"Open Folder", "Открыть папку"},
        {"Load Lua Script", "Загрузить Lua-скрипт"},
        {"Copy link", "Копировать ссылку"},
        {"Copy Path", "Копировать путь"},
        {"Discover Scripts", "Обновить список"},
        {"Refresh", "Обновить"},
        {"No Lua scripts found", "Lua-скрипты не найдены"},
        {"Copy scripts into the Lua directory", "Скопируйте скрипты в директорию Lua"},
        {"Autoload", "Автозагрузка"},
        {"Hot Reload", "Горячая перезагрузка"},
        {"Status", "Статус"},
        {"Runtime", "Выполнение"},
        {"Last Error", "Последняя ошибка"},
        {"Reload Script", "Перезагрузить скрипт"},
        {"Reload", "Перезагрузить"},

        // --- misc: general ----------------------------------------------
        {"AUTOMATION", "АВТОМАТИЗАЦИЯ"},
        {"Auto Accept Match", "Автопринятие матча"},
        {"GRENADES", "ГРАНАТЫ"},
        {"LINEUP HELPER", "ПОМОЩНИК РАСКИДОК"},
        {"GRENADE ASSIST", "ДОВОДКА ГРАНАТ"},
        {"TRAJECTORY", "ТРАЕКТОРИЯ"},
        {"Lineup Helper", "Раскидки"},
        {"Draw Distance", "Дистанция отрисовки"},
        {"Marker Distance", "Дистанция маркера"},
        {"Stand Radius", "Радиус точки"},
        {"Release Radius", "Точность позиции"},
        {"Height Tolerance", "Допуск по высоте"},
        {"Show Throw Type", "Тип броска"},
        {"Show Distance", "Дистанция"},
        {"Plaque Background", "Фон плашки"},
        {"Plaque Text", "Текст плашки"},
        {"Plaque Accent", "Акцент плашки"},
        {"Stand Marker", "Маркер точки"},
        {"Stand Marker Active", "Маркер точки (актив.)"},
        {"Aim Marker", "Маркер наведения"},
        {"Lineup Aim Assist", "Доводка на раскидку"},
        {"Aim Key", "Бинд доводки"},
        {"Auto Release", "Автоматический бросок"},
        {"Lock Threshold", "Порог захвата"},
        {"Settle Time", "Стабилизация"},
        {"Enemy Aim Assist", "Доводка гранаты по врагу"},
        {"Activation Key", "Бинд"},
        {"Target FOV", "FOV поиска"},
        {"Trajectory Preview", "Траектория"},
        {"Local Prediction Only", "Только свои гранаты"},
        {"Line Style", "Стиль линии"},
        {"Line Color", "Цвет линии"},
        {"Line Thickness", "Толщина линии"},
        {"Bloom", "Свечение"},
        {"Bloom Color", "Цвет свечения"},
        {"Bloom Radius", "Радиус свечения"},
        {"Bounce Points", "Точки отскока"},
        {"End Point", "Конечная точка"},
        {"Point Color", "Цвет точки"},
        {"Point Size", "Размер точки"},
        {"ENGINE", "ДВИЖОК"},
        {"FPS Limiter", "Лимит FPS"},
        {"Maximum FPS", "Максимум FPS"},
        {"INTERFACE", "ИНТЕРФЕЙС"},
        {"LANGUAGE", "ЯЗЫК"},
        {"Language", "Язык"},
        {"DPI Scale", "Масштаб DPI"},

        // --- misc: movement ---------------------------------------------
        {"BUNNY HOP", "BUNNY HOP"},
        {"EDGE JUMP", "EDGE JUMP"},
        {"Enable Bunny Hop", "Включить Bunny Hop"},
        {"Enable Edge Jump", "Включить Edge Jump"},

        // --- misc: effects ----------------------------------------------
        {"BULLET TRACERS", "ТРАССЕРЫ"},
        {"Enable Bullet Tracers", "Включить трассеры"},
        {"Tracer Color", "Цвет трассера"},
        {"Fade Duration", "Время затухания"},
        {"Max Tracers", "Макс. трассеров"},
        {"Bloom Effect", "Bloom"},
        {"Draw Impact Cubes", "Метки попаданий"},
        {"Draw Trajectory Line", "Линия траектории"},
        {"Cube Size", "Размер метки"},
        {"Fade Near", "Затухание вблизи"},
        {"Fade Far", "Затухание вдали"},

        // --- misc: overlay ----------------------------------------------
        {"CAPTURE", "ЗАХВАТ ЭКРАНА"},
        {"OBS Bypass", "Обход OBS"},
        {"WATERMARK", "ВОТЕРМАРКА"},
        {"Show Watermark", "Показывать"},
        {"Show Ping", "Пинг"},
        {"Show Loss", "Лосс"},
        {"Show CPU Load", "Нагрузка CPU"},
        {"Show FPS", "FPS"},

        {"SPECTATOR LIST", "НАБЛЮДАТЕЛИ"},
        {"Show Spectators", "Показывать"},
        {"EVENT LOG", "ЖУРНАЛ СОБЫТИЙ"},
        {"Event Log", "Журнал событий"},
        {"Show Event Log", "Показывать журнал"},
        {"Maximum Entries", "Количество записей"},
        {"Events", "События"},
        {"Shots", "Выстрелы"},
        {"Hits", "Попадания"},
        {"Kills", "Убийства"},
        {"Misses", "Промахи"},
        {"Blocked", "Блокировки"},
        {"Info", "Информация"},
        {"ACTIVE BINDS", "АКТИВНЫЕ БИНДЫ"},
        {"Active Binds", "Активные бинды"},
        {"Show Active Binds", "Показывать активные бинды"},
        {"Always On Binds", "Показывать постоянные"},
        {"Hold Binds", "Показывать удерживаемые"},
        {"Toggle Binds", "Показывать переключаемые"},
        {"BOMB PANEL", "ПАНЕЛЬ БОМБЫ"},
        {"Show Bomb Info", "Показывать информацию о бомбе"},
        {"No active entries", "Нет активных записей"},
        {"Spectators", "Наблюдатели"},

        {"Steam Avatars", "Аватары Steam"},
        {"  fixed camera", "  фикс. камера"},
        {"  first person", "  от первого лица"},
        {"  third person", "  от третьего лица"},
        {"  free camera", "  свободная камера"},

        // --- misc: configs ----------------------------------------------
        {"CFG FILE", "КОНФИГ"},
        {"File Name", "Имя файла"},
        {"Export Named CFG", "Сохранить"},
        {"Save As...", "Сохранить как..."},
        {"Open CFG", "Загрузить"},
        {"Browse...", "Обзор..."},

        // --- esp editor -------------------------------------------------
        {"ESP EDITOR", "РЕДАКТОР ESP"},
        {"PREVIEW UNAVAILABLE", "ПРЕДПРОСМОТР НЕДОСТУПЕН"},

        {"Manual lineup", "Ручная раскидка"},
        {"Hold {}, release", "Зажать {}, отпустить"},
        {"Hold {}, {}, release", "Зажать {}, {}, отпустить"},
        {"LMB", "ЛКМ"},
        {"RMB", "ПКМ"},
        {"LMB+RMB", "ЛКМ+ПКМ"},
        {"m", "м"},

        {"Jump+Throw", "Джамп троу"},
        {"W+Jump+Throw", "W+Джамп троу"},
        {"Run+Jump+Throw", "Бег+Джамп троу"},
        {"Walk+Jump+Throw", "Шаг+Джамп троу"},
        {"Crouch+Jump+Throw", "Присед+Джамп троу"},
        {"Crouch+W+Jump+Throw", "Присед+W+Джамп троу"},
        {"Crouch+Run+Jump+Throw", "Присед+Бег+Джамп троу"},
        {"WJump+Throw", "W+Джамп троу"},
        {"Jump+Throw LRMB", "Джамп троу ЛКМ+ПКМ"},
        {"Jump+Throw RMB", "Джамп троу ПКМ"},
        {"W+Jump+Throw LRMB", "W+Джамп троу ЛКМ+ПКМ"},
        {"W+Jump+Throw RMB", "W+Джамп троу ПКМ"},
        {"Run+Jump+Trhow", "Бег+Джамп троу"},
        {"W+Jump+Throwv", "W+Джамп троу"},
        {"Throw", "Бросок"},
        {"Throw LRMB", "Бросок ЛКМ+ПКМ"},
        {"Throw RMB", "Бросок ПКМ"},
        {"Throw (crouch)", "Бросок в приседе"},
        {"Throw (break glass)", "Бросок (разбить стекло)"},
        {"Run+Thorw", "Бросок в беге"},
        {"Run+Throw", "Бросок в беге"},
        {"Crouch+Run+Throw", "Присед+Бросок в беге"},
        {"Go Left then W+Jump+Throw", "Влево, затем W+Джамп троу"},
        {"Go Right then W+Jump+Throw", "Вправо, затем W+Джамп троу"},
        {"Complex, move left and back and jumpthrow while running",
         "Сложная: влево-назад, джамп троу в беге"},
        {"Insta Window (no autothrow)", "Insta Window (без автоброска)"},
        {"Insta Long Door (no autothrow)", "Insta Long Door (без автоброска)"},

        // Fallback tokens, used for any combination not spelled out above.
        {"Jump", "Прыжок"},
        {"Crouch", "Присед"},
        {"Run", "Бег"},
        {"Walk", "Шаг"},
        {"Step", "Шаг"},
        {"Forward", "Вперёд"},
        // The source table spells these wrong; kept verbatim as keys.
        {"Trhow", "Бросок"},
        {"Thorw", "Бросок"},
        {"Throwv", "Бросок"},
    };

    return table;
}

const std::unordered_map<std::string_view, const char *> &simplified_chinese()
{
    static const std::unordered_map<std::string_view, const char *> table{
        // --- navigation -------------------------------------------------
        {"Aimbot", "自瞄"},
        {"Triggerbot", "自动扳机"},
        {"Visuals", "透视"},
        {"Misc", "杂项"},

        // --- weapon group tabs ------------------------------------------
        {"Global", "全局"},
        {"Pistol", "手枪"},
        {"SMG", "冲锋枪"},
        {"Rifle", "步枪"},
        {"Shotgun", "霰弹枪"},
        {"Sniper", "狙击枪"},
        {"Heavy", "机枪"},

        // --- combat cards -----------------------------------------------
        {"TARGETING", "瞄准"},
        {"PENETRATION", "穿透"},
        {"VISUALIZATION", "显示"},
        {"TRIGGERBOT CORE", "扳机"},
        {"ADVANCED MODE", "高级模式"},
        // This card holds Auto Stop / Early Auto Stop -- it is about stopping
        // before the shot, not about the movement features in Misc.
        {"MOVEMENT", "急停"},
        {"OVERRIDE SETTINGS", "覆盖设置"},

        // --- combat rows ------------------------------------------------
        {"Master Switch", "总开关"},
        {"Activation", "激活方式"},
        {"Activation Mode", "激活模式"},
        {"Hold", "按住"},
        {"Always On", "始终开启"},
        {"Toggle", "切换"},
        {"Damage Override", "伤害覆盖"},
        {"Override Damage", "覆盖伤害"},
        {"Checks", "条件检查"},
        {"Jump", "跳跃"},
        {"Flash", "闪光"},
        {"Airborne", "空中"},
        {"Flashed", "被闪"},
        {"Threshold", "阈值"},
        {"Smoke", "烟雾"},
        {"Walls", "墙壁"},
        {"Block", "阻挡"},
        {"Penetration", "穿透"},
        {"Ignore", "忽略"},
        {"Trigger Key", "按键"},
        {"FOV", "FOV"},
        {"FOV Profile", "FOV 配置"},
        {"Radius", "半径"},
        {"Max Radius", "最大半径"},
        {"Min Radius", "最小半径"},
        {"Full Size At", "全尺寸距离"},
        {"Min Size At", "最小尺寸距离"},
        {"Advanced", "高级"},
        {"Fixed", "固定"},
        {"Distance", "距离"},
        {"Target", "目标"},
        {"Near Distance", "近距离"},
        {"Near FOV", "近距 FOV"},
        {"Far Distance", "远距离"},
        {"Far FOV", "远距 FOV"},
        {"Acquisition Area", "锁定区域"},
        {"Target Point", "瞄准点"},
        {"Show FOV", "显示 FOV"},
        {"Visualization", "可视化"},
        {"Smoothing", "平滑"},
        {"Humanize", "拟人化"},
        {"Humanizer Tuning", "拟人化调校"},
        {"Humanizer Profile", "拟人化配置"},
        {"Motion", "运动"},
        {"Behavior", "行为"},
        {"Gravity", "引力"},
        {"Wind", "偏移"},
        {"Max Step", "最大步长"},
        {"Damping", "阻尼"},
        {"Reaction Min", "最小反应"},
        {"Reaction Max", "最大反应"},
        {"Curve", "曲线"},
        {"Overshoot Chance", "过冲概率"},
        {"Overshoot Amount", "过冲幅度"},
        {"Jitter", "抖动"},
        {"Deadzone", "死区"},
        {"Hitboxes", "命中部位"},
        {"Multi-Point", "多点瞄准"},
        {"Cap Points", "端点"},
        {"Side Points", "侧点"},
        {"Head Scale", "头部比例"},
        {"Body Scale", "身体比例"},
        {"Limbs Scale", "四肢比例"},
        {"Prediction", "预判"},
        {"Max Horizon", "最大预测时长"},
        {"Acceleration", "考虑加速度"},
        {"RCS", "后坐力控制"},
        {"Start Bullet", "起始弹道"},
        {"Pitch Strength", "垂直力度"},
        {"Yaw Strength", "水平力度"},
        {"Humanization", "拟人化"},
        {"Response", "响应"},
        {"Gain Randomness", "力度随机"},
        {"Drift", "漂移"},
        {"Correction Time", "修正时间"},
        {"Smoothness", "平滑度"},
        {"Strength Variation", "力度变化"},
        {"Path Drift", "轨迹漂移"},
        {"Wall Policy", "穿墙策略"},
        {"Only Visible", "仅可见目标"},
        {"Shot Timing", "射击时机"},
        {"Randomize", "随机化"},
        {"Outlier Chance", "异常概率"},
        {"Outlier Delay", "异常延迟"},
        {"Lethal Only", "仅致命伤害"},
        {"R8 Readiness", "R8 就绪"},
        {"Release Margin", "松键余量"},
        {"Key", "按键"},
        {"Visible Only", "仅可见目标"},
        {"Predictive", "预测"},
        {"Recoil Sync", "后坐力同步"},
        {"Auto Wall", "自动穿墙"},
        {"Min Damage", "最低伤害"},
        {"Draw FOV Circle", "显示 FOV 圆圈"},
        {"Mode", "模式"},
        {"Interface Colors", "界面颜色"},
        {"Typography", "文字"},
        {"Primary Text", "主要文字"},
        {"Muted Text", "次要文字"},
        {"Surfaces", "表面"},
        {"Menu Background", "菜单背景"},
        {"Controls", "控件"},
        {"Containers", "容器"},
        {"Popups", "弹窗"},
        {"Interaction", "交互"},
        {"Accent", "强调色"},
        {"Hover", "悬停"},
        {"Borders", "边框"},
        {"Seed Type", "种子类型"},
        {"Hitchance", "命中率"},
        {"Delay (ms)", "延迟 (毫秒)"},
        {"Reaction Time (ms)", "反应时间 (毫秒)"},
        {"Auto Stop", "急停"},
        {"Early Auto Stop", "提前急停"},
        {"Delay Before", "前延迟"},
        {"Delay After", "后延迟"},
        {"Randomize (+-)", "随机 (±)"},
        {"Inherit Global Settings", "继承全局设置"},

        // --- shared option values ---------------------------------------
        {"Advanced", "高级"},
        {"None", "无"},
        {"All", "全部"},
        {"Restricted", "受限"},
        {"Unrestricted", "自由"},
        {"Head", "头部"},
        {"Body", "身体"},
        {"Arms", "手臂"},
        {"Legs", "腿部"},

        // --- visuals tabs -----------------------------------------------
        {"Players", "玩家"},
        {"Items", "物品"},
        {"Projectiles", "投掷物"},
        {"Bomb", "炸弹"},
        {"Radar", "雷达"},
        {"World", "世界"},
        {"Crosshair", "准星"},

        // --- expanded radar / crosshair ---------------------------------
        {"Player Names", "玩家名称"},
        {"Player Health", "玩家血量"},
        {"Player Armor", "玩家护甲"},
        {"Player Weapon", "玩家武器"},
        {"Grenade Markers", "投掷物标记"},
        {"Grenade Trajectories", "投掷物轨迹"},
        {"Grenade Zones", "投掷物范围"},
        {"Information Scale", "信息缩放"},
        {"Overlay Enemy Markers", "敌人标记"},
        {"Enemy Marker", "敌人标记"},
        {"View Direction", "视线方向"},
        {"Status Text", "状态文本"},
        {"Marker Scale", "标记缩放"},
        {"Text Outline", "文本描边"},
        {"HE Color", "手雷颜色"},
        {"Flash Color", "闪光弹颜色"},
        {"Smoke Color", "烟雾弹颜色"},
        {"Molotov Color", "燃烧弹颜色"},
        {"Decoy Color", "诱饵弹颜色"},
        {"Line Thickness", "线条粗细"},
        {"End Point Size", "终点大小"},
        {"Fill Opacity", "填充不透明度"},
        {"Outline Opacity", "描边不透明度"},
        {"In-Game Avatars", "游戏内头像"},
        {"Copy Game Crosshair", "复制游戏准星"},
        {"Outline Color", "描边颜色"},
        {"Outline Thickness", "描边粗细"},

        // --- player esp -------------------------------------------------
        {"MASTER", "主要"},
        {"BOUNDING BOX", "方框"},
        {"DETAILS", "详情"},
        {"SKELETON & HITBOXES", "骨骼与命中框"},
        {"Enable Player ESP", "启用玩家 ESP"},
        {"Legit Sync", "合法同步"},
        {"Spectator Sync", "观战者同步"},
        {"Direct Visibility", "直接可见"},
        {"Radar Spotted", "雷达暴露"},
        {"Audible Sounds", "可闻声"},
        {"Radar Hold", "雷达保持"},
        {"Sound Hold", "声音保持"},
        {"Hearing Distance", "可闻距离"},
        {"Pulse Minimum", "脉冲最小值"},
        {"Pulse Maximum", "脉冲最大值"},
        {"Pulse Period", "脉冲周期"},
        {"Show Box", "方框"},
        {"Style", "样式"},
        {"Full", "完整"},
        {"Cornered", "边角"},
        {"Corner Length", "边角长度"},
        {"Background Fill", "背景填充"},
        {"Box Visible Color", "方框:可见"},
        {"Box Occluded Color", "方框:隔墙"},
        {"Fill Visible Color", "填充:可见"},
        {"Fill Occluded Color", "填充:隔墙"},
        {"Show Name", "昵称"},
        {"Show Weapon", "武器"},
        {"Ammo Indicator", "弹药指示器"},
        {"Exact Ammo Count", "精确弹药数"},
        {"Empty Color", "空弹颜色"},
        {"Bomb Damage", "炸弹伤害"},
        {"Health Bar", "血条"},
        {"Ammo Bar", "弹药条"},
        {"Info Flags", "信息标记"},
        {"Chams", "上色"},
        {"Antialiasing", "抗锯齿"},
        {"Model Glow", "模型发光"},
        {"Glow Color", "发光颜色"},
        {"Glow Radius", "发光半径"},
        {"Glow Strength", "发光强度"},
        {"Glow Layers", "发光层数"},
        {"Death Shatter", "死亡碎裂"},
        {"On Hit Chams", "受击上色"},
        {"Kill Particles", "击杀粒子"},
        {"Particle Color", "粒子颜色"},
        {"Particle Duration", "粒子时长"},
        {"Particle Size", "粒子大小"},
        {"Particle Count", "粒子数量"},
        {"On Shot Chams", "开火上色"},
        {"Ghost Duration", "残影时长"},
        {"Ghost Appearance", "残影外观"},
        {"Occlusion", "遮挡"},
        {"Dynamic Doors", "动态门"},
        {"Smoke Occlusion", "烟雾遮挡"},
        {"Chams Visible", "上色:可见"},
        {"Chams Occluded", "上色:隔墙"},
        {"Show Skeleton", "骨骼"},
        {"Show Head Circle", "头部圆圈"},
        {"Show View Line", "视线线"},
        {"Offscreen Arrows", "屏外箭头"},
        {"Arrow Color", "箭头颜色"},
        {"Arrow Size", "箭头大小"},
        {"Arrow Radius", "箭头半径"},
        {"Bloom Speed", "光晕速度"},
        {"Minimum Glow", "最小光晕"},
        {"Maximum Glow", "最大光晕"},
        {"Threat Hitboxes", "威胁命中框"},
        {"SOUND ESP", "声音 ESP"},
        {"Sound ESP", "声音 ESP"},
        {"Enable Sound ESP", "启用声音 ESP"},
        {"Ring Color", "圆环颜色"},
        {"Local Sync", "本地同步"},
        {"Duration", "持续时间"},
        {"Ring Radius", "圆环半径"},
        {"Audible Distance", "可闻距离"},
        {"Head Hitbox Color", "颜色:头部"},
        {"Body Hitbox Color", "颜色:身体"},
        {"Fill Alpha", "填充透明度"},

        // --- chams materials --------------------------------------------
        {"Material", "材质"},
        {"Color", "颜色"},
        {"Wireframe", "线框"},
        {"Roughness", "粗糙度"},
        {"Metalness", "金属度"},
        {"Exponent", "指数"},
        {"Falloff", "衰减"},
        {"Fresnel Filling", "菲涅尔填充"},
        {"Strength", "强度"},
        {"Speed", "速度"},
        {"Tint", "色调"},
        {"Solid", "纯色"},
        {"Shaded", "阴影"},
        {"Glow", "发光"},

        {"Glow Outline", "发光描边"},
        {"Iridescent", "虹彩"},
        {"Water Flow", "水流"},
        {"Glossy", "光泽"},

        // --- item esp ---------------------------------------------------
        {"SETTINGS", "设置"},
        {"FILTERS", "筛选"},
        {"Enable Item ESP", "启用物品 ESP"},
        {"Max Distance", "最大距离"},
        {"Show Icon", "图标"},
        {"Show Item Name", "物品名称"},
        {"Rifles", "步枪"},
        {"SMGs", "冲锋枪"},
        {"Snipers", "狙击枪"},
        {"Pistols", "手枪"},
        {"Grenades", "投掷物"},
        {"Utility", "道具"},

        // --- projectile esp ---------------------------------------------
        {"VISUAL ELEMENTS", "显示元素"},
        {"COLORS", "颜色"},
        {"Enable Projectiles", "启用投掷物 ESP"},
        {"Display Mode", "显示模式"},
        {"Indicator", "指示器"},
        {"Text Only", "仅文本"},
        {"Show Text", "显示文本"},
        {"Effect Timer", "效果计时"},
        {"Effect Timer Ring", "计时圆环"},
        {"Inferno Bounds", "燃烧范围"},
        {"INDICATOR", "指示器"},
        {"Timer Full", "计时:满"},
        {"Timer Low", "计时:低"},
        {"Indicator Background", "指示器背景"},
        {"INFERNO GRADIENT", "燃烧渐变"},
        {"Gradient Width", "渐变宽度"},
        {"Gradient Opacity", "渐变亮度"},
        {"HE Grenade", "手雷"},
        {"Flashbang", "闪光弹"},
        {"Smoke", "烟雾弹"},
        {"Molotov", "燃烧弹"},
        {"Decoy", "诱饵弹"},

        // --- bomb esp ---------------------------------------------------
        {"STATES", "状态"},
        {"SAFE ZONE (BAKED)", "安全区"},
        {"Enable Bomb ESP", "启用炸弹 ESP"},
        {"Show Carrier", "显示携带者"},
        {"Show Planted", "显示已安放"},
        {"Planted Color", "已安放颜色"},
        {"Defusing Color", "拆弹颜色"},
        {"Panel Background", "面板背景"},
        {"World Timer Ring", "世界计时圆环"},
        {"World Timer", "世界计时器"},
        {"Bomb Info Panel", "炸弹信息面板"},
        {"Timer Color", "计时器颜色"},
        {"Safe Zone Contour", "安全区轮廓"},
        {"Zone Color", "区域颜色"},
        {"Gradient Bands", "渐变带"},
        {"Band Step", "渐变带间距"},

        // --- radar / world ----------------------------------------------
        {"RADAR OVERLAY", "雷达"},
        {"Overlay Enemy Markers", "敌人标记"},
        {"NO FLASH (WIREFRAME)", "无闪光 (线框)"},
        {"Enable Visual No Flash", "启用视觉无闪光"},
        {"Render Distance", "渲染距离"},
        {"Dimming Overlay Color", "变暗颜色"},
        {"Wireframe Color", "线框颜色"},
        {"NO SMOKE (WIREFRAME)", "无烟雾 (线框)"},
        {"Enable Visual No Smoke", "启用视觉无烟雾"},
        {"Smoke Wireframe Color", "烟雾线框颜色"},

        // --- crosshair --------------------------------------------------
        {"CROSSHAIR SETTINGS", "准星设置"},
        {"Enable Crosshair", "启用准星"},
        {"Weapon Sync", "武器同步"},
        {"Draw Dot", "中心点"},
        {"Draw Lines", "准星线"},
        {"T-Style", "T 型"},
        {"Length", "长度"},
        {"Gap", "间距"},
        {"Thickness", "粗细"},
        {"Draw Outline", "描边"},
        {"Primary Color", "主色"},
        {"Penetration Indicator", "穿透指示器"},
        {"Can Penetrate", "可穿透"},
        {"Cannot Penetrate", "不可穿透"},

        // --- misc tabs --------------------------------------------------
        {"General", "常规"},
        {"Movement", "移动"},
        {"Effects", "效果"},
        {"Overlay", "覆盖层"},
        {"Lua API", "Lua API"},
        {"Configs", "配置"},
        {"LUA RUNTIME", "LUA 运行时"},
        {"SCRIPTS", "脚本"},
        {"Enable Lua API", "启用 Lua API"},
        {"Script Directory", "脚本目录"},
        {"Open Folder", "打开文件夹"},
        {"Load Lua Script", "加载 Lua 脚本"},
        {"Copy link", "复制链接"},
        {"Copy Path", "复制路径"},
        {"Discover Scripts", "刷新列表"},
        {"Refresh", "刷新"},
        {"No Lua scripts found", "未找到 Lua 脚本"},
        {"Copy scripts into the Lua directory", "请将脚本复制到 Lua 目录"},
        {"Autoload", "自动加载"},
        {"Hot Reload", "热重载"},
        {"Status", "状态"},
        {"Runtime", "运行时"},
        {"Last Error", "最后错误"},
        {"Reload Script", "重载脚本"},
        {"Reload", "重载"},

        // --- misc: general ----------------------------------------------
        {"AUTOMATION", "自动化"},
        {"Auto Accept Match", "自动接受对局"},
        {"GRENADES", "投掷物"},
        {"LINEUP HELPER", "道具点位助手"},
        {"GRENADE ASSIST", "投掷物辅助"},
        {"TRAJECTORY", "弹道"},
        {"Lineup Helper", "道具点位"},
        {"Draw Distance", "绘制距离"},
        {"Marker Distance", "标记距离"},
        {"Stand Radius", "站位半径"},
        {"Release Radius", "松键半径"},
        {"Height Tolerance", "高度容差"},
        {"Show Throw Type", "显示投掷方式"},
        {"Show Distance", "显示距离"},
        {"Plaque Background", "提示牌背景"},
        {"Plaque Text", "提示牌文字"},
        {"Plaque Accent", "提示牌强调色"},
        {"Stand Marker", "站位标记"},
        {"Stand Marker Active", "站位标记 (激活)"},
        {"Aim Marker", "瞄准标记"},
        {"Lineup Aim Assist", "点位瞄准辅助"},
        {"Aim Key", "瞄准键"},
        {"Auto Release", "自动投掷"},
        {"Lock Threshold", "锁定阈值"},
        {"Settle Time", "稳定时间"},
        {"Enemy Aim Assist", "敌人投掷辅助"},
        {"Activation Key", "激活键"},
        {"Target FOV", "目标 FOV"},
        {"Trajectory Preview", "弹道预览"},
        {"Local Prediction Only", "仅本地投掷"},
        {"Line Style", "线条样式"},
        {"Line Color", "线条颜色"},
        {"Line Thickness", "线条粗细"},
        {"Bloom", "光晕"},
        {"Bloom Color", "光晕颜色"},
        {"Bloom Radius", "光晕半径"},
        {"Bounce Points", "反弹点"},
        {"End Point", "终点"},
        {"Point Color", "点颜色"},
        {"Point Size", "点大小"},
        {"ENGINE", "引擎"},
        {"FPS Limiter", "帧率限制"},
        {"Maximum FPS", "最大帧率"},
        {"INTERFACE", "界面"},
        {"LANGUAGE", "语言"},
        {"Language", "语言"},
        {"DPI Scale", "DPI 缩放"},

        // --- misc: movement ---------------------------------------------
        {"BUNNY HOP", "连跳"},
        {"EDGE JUMP", "边缘跳"},
        {"Enable Bunny Hop", "启用连跳"},
        {"Enable Edge Jump", "启用边缘跳"},

        // --- misc: effects ----------------------------------------------
        {"BULLET TRACERS", "弹道曳光"},
        {"Enable Bullet Tracers", "启用曳光弹"},
        {"Tracer Color", "曳光颜色"},
        {"Fade Duration", "淡出时长"},
        {"Max Tracers", "最大曳光数"},
        {"Bloom Effect", "光晕效果"},
        {"Draw Impact Cubes", "命中方块"},
        {"Draw Trajectory Line", "弹道线"},
        {"Cube Size", "方块大小"},
        {"Fade Near", "近距淡出"},
        {"Fade Far", "远距淡出"},

        // --- misc: overlay ----------------------------------------------
        {"CAPTURE", "捕获"},
        {"OBS Bypass", "绕过 OBS"},
        {"WATERMARK", "水印"},
        {"Show Watermark", "显示水印"},
        {"Show Ping", "显示延迟"},
        {"Show Loss", "显示丢包"},
        {"Show CPU Load", "显示 CPU 占用"},
        {"Show FPS", "显示 FPS"},

        {"SPECTATOR LIST", "观战列表"},
        {"Show Spectators", "显示观战者"},
        {"EVENT LOG", "事件日志"},
        {"Event Log", "事件日志"},
        {"Show Event Log", "显示事件日志"},
        {"Maximum Entries", "最大条目数"},
        {"Events", "事件"},
        {"Shots", "开枪"},
        {"Hits", "命中"},
        {"Kills", "击杀"},
        {"Misses", "落空"},
        {"Blocked", "阻挡"},
        {"Info", "信息"},
        {"ACTIVE BINDS", "激活的按键"},
        {"Active Binds", "激活的按键"},
        {"Show Active Binds", "显示激活按键"},
        {"Always On Binds", "常开按键"},
        {"Hold Binds", "按住按键"},
        {"Toggle Binds", "切换按键"},
        {"BOMB PANEL", "炸弹面板"},
        {"Show Bomb Info", "显示炸弹信息"},
        {"No active entries", "暂无活动条目"},
        {"Spectators", "观战者"},

        {"Steam Avatars", "Steam 头像"},
        {"  fixed camera", "  固定镜头"},
        {"  first person", "  第一人称"},
        {"  third person", "  第三人称"},
        {"  free camera", "  自由镜头"},

        // --- misc: configs ----------------------------------------------
        {"CFG FILE", "配置文件"},
        {"File Name", "文件名"},
        {"Export Named CFG", "保存"},
        {"Save As...", "另存为..."},
        {"Open CFG", "加载"},
        {"Browse...", "浏览..."},

        // --- esp editor -------------------------------------------------
        {"ESP EDITOR", "ESP 编辑器"},
        {"PREVIEW UNAVAILABLE", "预览不可用"},

        {"Manual lineup", "手动点位"},
        {"Hold {}, release", "按住 {}, 松开"},
        {"Hold {}, {}, release", "按住 {}, {}, 松开"},
        {"LMB", "左键"},
        {"RMB", "右键"},
        {"LMB+RMB", "左键+右键"},
        {"m", "米"},

        {"Jump+Throw", "跳投"},
        {"W+Jump+Throw", "W+跳投"},
        {"Run+Jump+Throw", "跑动跳投"},
        {"Walk+Jump+Throw", "行走跳投"},
        {"Crouch+Jump+Throw", "蹲跳投"},
        {"Crouch+W+Jump+Throw", "蹲+W+跳投"},
        {"Crouch+Run+Jump+Throw", "蹲+跑动跳投"},
        {"WJump+Throw", "W+跳投"},
        {"Jump+Throw LRMB", "跳投 左键+右键"},
        {"Jump+Throw RMB", "跳投 右键"},
        {"W+Jump+Throw LRMB", "W+跳投 左键+右键"},
        {"W+Jump+Throw RMB", "W+跳投 右键"},
        {"Run+Jump+Trhow", "跑动跳投"},
        {"W+Jump+Throwv", "W+跳投"},
        {"Throw", "投掷"},
        {"Throw LRMB", "投掷 左键+右键"},
        {"Throw RMB", "投掷 右键"},
        {"Throw (crouch)", "下蹲投掷"},
        {"Throw (break glass)", "投掷 (碎玻璃)"},
        {"Run+Thorw", "跑动投掷"},
        {"Run+Throw", "跑动投掷"},
        {"Crouch+Run+Throw", "蹲+跑动投掷"},
        {"Go Left then W+Jump+Throw", "先左移, 再 W+跳投"},
        {"Go Right then W+Jump+Throw", "先右移, 再 W+跳投"},
        {"Complex, move left and back and jumpthrow while running",
         "复杂: 左移后退, 跑动跳投"},
        {"Insta Window (no autothrow)", "瞬时窗口 (无自动投掷)"},
        {"Insta Long Door (no autothrow)", "瞬时长门 (无自动投掷)"},

        // Fallback tokens, used for any combination not spelled out above.
        {"Jump", "跳跃"},
        {"Crouch", "下蹲"},
        {"Run", "跑动"},
        {"Walk", "行走"},
        {"Step", "步"},
        {"Forward", "前进"},
        // The source table spells these wrong; kept verbatim as keys.
        {"Trhow", "投掷"},
        {"Thorw", "投掷"},
        {"Throwv", "投掷"},

        // --- feature descriptions (tooltips) -----------------------------
        {"Adds a configurable delay and randomization before and after each trigger shot.",
         "在每次扳机开火前后加入可调的延迟与随机化。"},
        {"Fires ahead of moving targets by simulating where they will be when the bullet lands.",
         "通过模拟子弹命中时目标的位置, 提前向移动目标开火。"},
        {"Turns the combat feature on and controls whether it is always on, held or toggled.",
         "开启该战斗功能, 并控制它为常开、按住或切换触发。"},
        {"Only fires when a shot can deal at least the configured damage to the target.",
         "只有当这一枪能对目标造成至少设定伤害时才会开火。"},
        {"Limits how far from the crosshair targets can be picked; open for radius modes.",
         "限制准星多远范围内的目标会被选取; 打开查看半径模式。"},
        {"Blends in human aim traits like reaction delay, overshoot and jitter on top of the aim path.",
         "在瞄准轨迹上叠加人类瞄准特征, 如反应延迟、过冲与抖动。"},
        {"Adds extra aim points on each hitbox and can scale them per body part.",
         "为每个命中框添加额外瞄准点, 并可按身体部位缩放。"},
        {"Compensates weapon recoil automatically with per-axis strength and human-like variation.",
         "自动补偿武器后坐力, 可按轴向设定强度并带有人类化差异。"},
        {"Draws boxes, health, weapons and more for every visible enemy on your screen.",
         "为屏幕上每个可见敌人绘制方框、血量、武器等信息。"},
        {"Makes enemies appear spotted on radar, visible and audible like legit information.",
         "让敌人在雷达上显示被点亮, 并以合法信息的样式显示可见与可听状态。"},
        {"Draws the bullet flight path between your shots and their impact points.",
         "绘制从你的开火位置到弹着点的子弹飞行轨迹。"},
        {"Plays a hit confirmation sound and can show floating damage numbers.",
         "播放命中确认音效, 并可显示浮动伤害数字。"},
        {"Switches the whole interface language; applies immediately and is saved to the config.",
         "切换整个界面语言; 立即生效并保存到配置。"},
        {"Scales the entire menu up or down without changing in-game rendering.",
         "整体缩放菜单大小, 不影响游戏内渲染。"},
        {"Customizes every menu color: text, panels, popups, accent and borders.",
         "自定义菜单的每种颜色: 文字、面板、弹窗、强调色与边框。"},
        {"Caps the overlay frame rate to reduce CPU and GPU usage.",
         "限制悬浮窗帧率, 降低 CPU 与 GPU 占用。"},
        {"Guides you through grenade lineups with on-screen stand and aim markers.",
         "通过屏幕上的站位与瞄准标记引导你完成手榴弹点位。"},
        {"Aligns your view to the lineup and can release the grenade automatically.",
         "将视角对齐到点位, 并可自动松手投掷。"},
        {"Steers your aim toward enemies while throwing grenades.",
         "投掷手榴弹时将你的瞄准引导向敌人。"},
        {"Draws the predicted grenade flight path, bounces and landing point.",
         "绘制预测的手榴弹飞行轨迹、弹跳点与落点。"},
        {"Automatically jumps the moment you touch the ground while holding the key.",
         "按住按键时, 一触地就自动跳跃。"},
        {"Jumps at the exact edge of a platform for maximum jump distance.",
         "在平台边缘的精确瞬间起跳, 达到最大跳跃距离。"},
        {"Halts your movement automatically before shots to make them fully accurate.",
         "开火前自动停止移动, 让每一枪完全精准。"},
        {"Shows a small performance plaque with ping, loss, CPU load and FPS.",
         "显示一个小型性能铭牌, 包含延迟、丢包、CPU 负载与 FPS。"},
        {"Logs shots, hits, kills and other events in a compact list.",
         "以紧凑列表记录开火、命中、击杀等事件。"},
        {"Lists every active keybind on screen so you always know what is enabled.",
         "在屏幕上列出所有生效的按键绑定, 让你随时了解开启的功能。"},
        {"Tints the inside of the player box with separate colors for visible and occluded states.",
         "为玩家方框内部着色, 可见与被遮挡状态使用不同颜色。"},
        {"Draws the enemy's current weapon next to their box.",
         "在敌人方框旁显示其当前武器。"},
        {"Shows a health bar beside the player with a configurable layout.",
         "在玩家旁显示血条, 布局可配置。"},
        {"Shows an armor bar beside the player with a configurable layout.",
         "在玩家旁显示护甲条, 布局可配置。"},
        {"Displays text flags like money, flash, kit and scoped state.",
         "显示金钱、被闪、护甲包、开镜状态等文字标记。"},
        {"Makes the enemy model emit light through walls with a configurable color and radius.",
         "让敌人模型透过墙壁发光, 颜色与半径可配置。"},
        {"Bursts the enemy model into particles when they die.",
         "敌人死亡时将其模型爆散为粒子效果。"},
        {"Points toward enemies that are outside your view so you never lose their position.",
         "指向视野外的敌人, 让你不会丢失其位置。"},
        {"Highlights the enemy's head and body hitboxes through walls.",
         "透视显示敌人的头部与身体命中框。"},
        {"Draws a fading ring where footsteps and other sounds happen.",
         "在脚步与其他声音发生处绘制逐渐消散的圆环。"},
        {"Shows a fading ghost of the enemy model at the spot of each hit.",
         "在每次命中的位置显示敌人模型逐渐消散的残影。"},
        {"Material applied to enemies you can currently see.",
         "应用于当前可见敌人的材质。"},
        {"Material applied to enemies hidden behind walls or smoke.",
         "应用于被墙壁或烟雾遮挡的敌人的材质。"},
        {"Highlights dropped weapons and gear on the ground.",
         "高亮地面上的掉落武器与装备。"},
        {"Labels each dropped item with its weapon name.",
         "为每个掉落物标注武器名称。"},
        {"Shows live grenades and their timers for both teams.",
         "显示双方存活中的手榴弹及其计时。"},
        {"Chooses between a colored icon and a text label for projectiles.",
         "选择投掷物使用彩色图标还是文字标签。"},
        {"Outlines the area burning from a Molotov or Incendiary.",
         "勾画出燃烧瓶或燃烧弹的燃烧范围。"},
        {"Marks the planted bomb on the world with its defuse timer.",
         "在场景中标记已安放的炸弹及其拆除计时。"},
        {"Shows a compact panel with the bomb timer and defuse progress.",
         "显示包含炸弹计时与拆除进度的紧凑面板。"},
        {"Outlines how far the bomb blast can still deal damage.",
         "勾画出炸弹爆炸仍能造成伤害的范围。"},
        {"Draws enemy positions, health and weapons on the in-game radar.",
         "在游戏内雷达上绘制敌人位置、血量与武器。"},
        {"Adds an outline to radar text for readability.",
         "为雷达文字添加描边, 提升可读性。"},
        {"Shows grenade icons on the radar with per-type colors.",
         "在雷达上显示手榴弹图标, 按类型着色。"},
        {"Draws predicted grenade flight paths on the radar.",
         "在雷达上绘制预测的手榴弹飞行轨迹。"},
        {"Shows grenade effect zones like smoke and molotov areas on the radar.",
         "在雷达上显示烟雾、燃烧区等手榴弹效果范围。"},
        {"Draws a marker at the impact point of each confirmed hit.",
         "在每次确认命中的弹着点绘制标记。"},
        {"Draws a wireframe world while flashed so you keep your orientation.",
         "被闪白时以线框绘制场景, 保持方向感。"},
        {"Draws smoke volumes as wireframes so you can see through them.",
         "将烟雾体积绘制为线框, 让你能看穿烟雾。"},
        {"Draws the crosshair line segments with adjustable length and gap.",
         "绘制准星线段, 长度与间隙可调。"},
        {"Adds an outline around the crosshair for visibility on any background.",
         "为准星添加描边, 在任何背景下都清晰可见。"},
        {"Colors the crosshair to show whether the wall between you and the target can be penetrated.",
         "为准星着色, 提示你与目标之间的墙壁是否可穿透。"},
    };

    return table;
}

const std::unordered_map<std::string_view, const char *> &traditional_chinese()
{
    static const std::unordered_map<std::string_view, const char *> table{
        // --- navigation -------------------------------------------------
        {"Aimbot", "自瞄"},
        {"Triggerbot", "自動扳機"},
        {"Visuals", "透視"},
        {"Misc", "雜項"},

        // --- weapon group tabs ------------------------------------------
        {"Global", "全域"},
        {"Pistol", "手槍"},
        {"SMG", "衝鋒槍"},
        {"Rifle", "步槍"},
        {"Shotgun", "霰彈槍"},
        {"Sniper", "狙擊槍"},
        {"Heavy", "機槍"},

        // --- combat cards -----------------------------------------------
        {"TARGETING", "瞄準"},
        {"PENETRATION", "穿透"},
        {"VISUALIZATION", "顯示"},
        {"TRIGGERBOT CORE", "扳機"},
        {"ADVANCED MODE", "進階模式"},
        // This card holds Auto Stop / Early Auto Stop -- it is about stopping
        // before the shot, not about the movement features in Misc.
        {"MOVEMENT", "急停"},
        {"OVERRIDE SETTINGS", "覆蓋設定"},

        // --- combat rows ------------------------------------------------
        {"Master Switch", "總開關"},
        {"Activation", "觸發方式"},
        {"Activation Mode", "觸發模式"},
        {"Hold", "按住"},
        {"Always On", "永遠開啟"},
        {"Toggle", "切換"},
        {"Damage Override", "傷害覆蓋"},
        {"Override Damage", "覆蓋傷害"},
        {"Checks", "條件檢查"},
        {"Jump", "跳躍"},
        {"Flash", "閃光"},
        {"Airborne", "空中"},
        {"Flashed", "被閃"},
        {"Threshold", "閾值"},
        {"Smoke", "煙霧"},
        {"Walls", "牆壁"},
        {"Block", "阻擋"},
        {"Penetration", "穿透"},
        {"Ignore", "忽略"},
        {"Trigger Key", "按鍵"},
        {"FOV", "FOV"},
        {"FOV Profile", "FOV 設定"},
        {"Radius", "半徑"},
        {"Max Radius", "最大半徑"},
        {"Min Radius", "最小半徑"},
        {"Full Size At", "全尺寸距離"},
        {"Min Size At", "最小尺寸距離"},
        {"Advanced", "進階"},
        {"Fixed", "固定"},
        {"Distance", "距離"},
        {"Target", "目標"},
        {"Near Distance", "近距離"},
        {"Near FOV", "近距 FOV"},
        {"Far Distance", "遠距離"},
        {"Far FOV", "遠距 FOV"},
        {"Acquisition Area", "鎖定區域"},
        {"Target Point", "瞄準點"},
        {"Show FOV", "顯示 FOV"},
        {"Visualization", "視覺化"},
        {"Smoothing", "平滑"},
        {"Humanize", "擬人化"},
        {"Humanizer Tuning", "擬人化調校"},
        {"Humanizer Profile", "擬人化設定"},
        {"Motion", "運動"},
        {"Behavior", "行為"},
        {"Gravity", "引力"},
        {"Wind", "偏移"},
        {"Max Step", "最大步長"},
        {"Damping", "阻尼"},
        {"Reaction Min", "最小反應"},
        {"Reaction Max", "最大反應"},
        {"Curve", "曲線"},
        {"Overshoot Chance", "過衝機率"},
        {"Overshoot Amount", "過衝幅度"},
        {"Jitter", "抖動"},
        {"Deadzone", "死區"},
        {"Hitboxes", "命中部位"},
        {"Multi-Point", "多點瞄準"},
        {"Cap Points", "端點"},
        {"Side Points", "側點"},
        {"Head Scale", "頭部比例"},
        {"Body Scale", "身體比例"},
        {"Limbs Scale", "四肢比例"},
        {"Prediction", "預判"},
        {"Max Horizon", "最大預測時長"},
        {"Acceleration", "考慮加速度"},
        {"RCS", "後座力控制"},
        {"Start Bullet", "起始彈道"},
        {"Pitch Strength", "垂直力度"},
        {"Yaw Strength", "水平力度"},
        {"Humanization", "擬人化"},
        {"Response", "響應"},
        {"Gain Randomness", "力度隨機"},
        {"Drift", "漂移"},
        {"Correction Time", "修正時間"},
        {"Smoothness", "平滑度"},
        {"Strength Variation", "力度變化"},
        {"Path Drift", "軌跡漂移"},
        {"Wall Policy", "穿牆策略"},
        {"Only Visible", "僅可見目標"},
        {"Shot Timing", "射擊時機"},
        {"Randomize", "隨機化"},
        {"Outlier Chance", "異常機率"},
        {"Outlier Delay", "異常延遲"},
        {"Lethal Only", "僅致命傷害"},
        {"R8 Readiness", "R8 就緒"},
        {"Release Margin", "鬆鍵餘量"},
        {"Key", "按鍵"},
        {"Visible Only", "僅可見目標"},
        {"Predictive", "預測"},
        {"Recoil Sync", "後座力同步"},
        {"Auto Wall", "自動穿牆"},
        {"Min Damage", "最低傷害"},
        {"Draw FOV Circle", "顯示 FOV 圓圈"},
        {"Mode", "模式"},
        {"Interface Colors", "介面顏色"},
        {"Typography", "文字"},
        {"Primary Text", "主要文字"},
        {"Muted Text", "次要文字"},
        {"Surfaces", "表面"},
        {"Menu Background", "選單背景"},
        {"Controls", "控制項"},
        {"Containers", "容器"},
        {"Popups", "彈出視窗"},
        {"Interaction", "互動"},
        {"Accent", "強調色"},
        {"Hover", "懸停"},
        {"Borders", "邊框"},
        {"Seed Type", "種子類型"},
        {"Hitchance", "命中率"},
        {"Delay (ms)", "延遲 (毫秒)"},
        {"Reaction Time (ms)", "反應時間 (毫秒)"},
        {"Auto Stop", "急停"},
        {"Early Auto Stop", "提前急停"},
        {"Delay Before", "前延遲"},
        {"Delay After", "後延遲"},
        {"Randomize (+-)", "隨機 (±)"},
        {"Inherit Global Settings", "繼承全域設定"},

        // --- shared option values ---------------------------------------
        {"Advanced", "進階"},
        {"None", "無"},
        {"All", "全部"},
        {"Restricted", "受限"},
        {"Unrestricted", "自由"},
        {"Head", "頭部"},
        {"Body", "身體"},
        {"Arms", "手臂"},
        {"Legs", "腿部"},

        // --- visuals tabs -----------------------------------------------
        {"Players", "玩家"},
        {"Items", "物品"},
        {"Projectiles", "投擲物"},
        {"Bomb", "炸彈"},
        {"Radar", "雷達"},
        {"World", "世界"},
        {"Crosshair", "準心"},

        // --- expanded radar / crosshair ---------------------------------
        {"Player Names", "玩家名稱"},
        {"Player Health", "玩家血量"},
        {"Player Armor", "玩家護甲"},
        {"Player Weapon", "玩家武器"},
        {"Grenade Markers", "投擲物標記"},
        {"Grenade Trajectories", "投擲物軌跡"},
        {"Grenade Zones", "投擲物範圍"},
        {"Information Scale", "資訊縮放"},
        {"Overlay Enemy Markers", "敵人標記"},
        {"Enemy Marker", "敵人標記"},
        {"View Direction", "視線方向"},
        {"Status Text", "狀態文字"},
        {"Marker Scale", "標記縮放"},
        {"Text Outline", "文字描邊"},
        {"HE Color", "手榴彈顏色"},
        {"Flash Color", "閃光彈顏色"},
        {"Smoke Color", "煙霧彈顏色"},
        {"Molotov Color", "燃燒彈顏色"},
        {"Decoy Color", "誘餌彈顏色"},
        {"Line Thickness", "線條粗細"},
        {"End Point Size", "終點大小"},
        {"Fill Opacity", "填充不透明度"},
        {"Outline Opacity", "描邊不透明度"},
        {"In-Game Avatars", "遊戲內頭像"},
        {"Copy Game Crosshair", "複製遊戲準心"},
        {"Outline Color", "描邊顏色"},
        {"Outline Thickness", "描邊粗細"},

        // --- player esp -------------------------------------------------
        {"MASTER", "主要"},
        {"BOUNDING BOX", "方框"},
        {"DETAILS", "詳情"},
        {"SKELETON & HITBOXES", "骨骼與命中框"},
        {"Enable Player ESP", "啟用玩家 ESP"},
        {"Legit Sync", "合法同步"},
        {"Spectator Sync", "觀戰者同步"},
        {"Direct Visibility", "直接可見"},
        {"Radar Spotted", "雷達暴露"},
        {"Audible Sounds", "可聞聲"},
        {"Radar Hold", "雷達保持"},
        {"Sound Hold", "聲音保持"},
        {"Hearing Distance", "可聞距離"},
        {"Pulse Minimum", "脈衝最小值"},
        {"Pulse Maximum", "脈衝最大值"},
        {"Pulse Period", "脈衝週期"},
        {"Show Box", "方框"},
        {"Style", "樣式"},
        {"Full", "完整"},
        {"Cornered", "邊角"},
        {"Corner Length", "邊角長度"},
        {"Background Fill", "背景填充"},
        {"Box Visible Color", "方框:可見"},
        {"Box Occluded Color", "方框:隔牆"},
        {"Fill Visible Color", "填充:可見"},
        {"Fill Occluded Color", "填充:隔牆"},
        {"Show Name", "暱稱"},
        {"Show Weapon", "武器"},
        {"Ammo Indicator", "彈藥指示器"},
        {"Exact Ammo Count", "精確彈藥數"},
        {"Empty Color", "空彈顏色"},
        {"Bomb Damage", "炸彈傷害"},
        {"Health Bar", "血條"},
        {"Ammo Bar", "彈藥條"},
        {"Info Flags", "資訊標記"},
        {"Chams", "上色"},
        {"Antialiasing", "抗鋸齒"},
        {"Model Glow", "模型發光"},
        {"Glow Color", "發光顏色"},
        {"Glow Radius", "發光半徑"},
        {"Glow Strength", "發光強度"},
        {"Glow Layers", "發光層數"},
        {"Death Shatter", "死亡碎裂"},
        {"On Hit Chams", "受擊上色"},
        {"Kill Particles", "擊殺粒子"},
        {"Particle Color", "粒子顏色"},
        {"Particle Duration", "粒子時長"},
        {"Particle Size", "粒子大小"},
        {"Particle Count", "粒子數量"},
        {"On Shot Chams", "開火上色"},
        {"Ghost Duration", "殘影時長"},
        {"Ghost Appearance", "殘影外觀"},
        {"Occlusion", "遮擋"},
        {"Dynamic Doors", "動態門"},
        {"Smoke Occlusion", "煙霧遮擋"},
        {"Chams Visible", "上色:可見"},
        {"Chams Occluded", "上色:隔牆"},
        {"Show Skeleton", "骨骼"},
        {"Show Head Circle", "頭部圓圈"},
        {"Show View Line", "視線線"},
        {"Offscreen Arrows", "屏外箭頭"},
        {"Arrow Color", "箭頭顏色"},
        {"Arrow Size", "箭頭大小"},
        {"Arrow Radius", "箭頭半徑"},
        {"Bloom Speed", "光暈速度"},
        {"Minimum Glow", "最小光暈"},
        {"Maximum Glow", "最大光暈"},
        {"Threat Hitboxes", "威脅命中框"},
        {"SOUND ESP", "聲音 ESP"},
        {"Sound ESP", "聲音 ESP"},
        {"Enable Sound ESP", "啟用聲音 ESP"},
        {"Ring Color", "圓環顏色"},
        {"Local Sync", "本地同步"},
        {"Duration", "持續時間"},
        {"Ring Radius", "圓環半徑"},
        {"Audible Distance", "可聞距離"},
        {"Head Hitbox Color", "顏色:頭部"},
        {"Body Hitbox Color", "顏色:身體"},
        {"Fill Alpha", "填充透明度"},

        // --- chams materials --------------------------------------------
        {"Material", "材質"},
        {"Color", "顏色"},
        {"Wireframe", "線框"},
        {"Roughness", "粗糙度"},
        {"Metalness", "金屬度"},
        {"Exponent", "指數"},
        {"Falloff", "衰減"},
        {"Fresnel Filling", "菲涅耳填充"},
        {"Strength", "強度"},
        {"Speed", "速度"},
        {"Tint", "色調"},
        {"Solid", "純色"},
        {"Shaded", "陰影"},
        {"Glow", "發光"},

        {"Glow Outline", "發光描邊"},
        {"Iridescent", "虹彩"},
        {"Water Flow", "水流"},
        {"Glossy", "光澤"},

        // --- item esp ---------------------------------------------------
        {"SETTINGS", "設定"},
        {"FILTERS", "篩選"},
        {"Enable Item ESP", "啟用物品 ESP"},
        {"Max Distance", "最大距離"},
        {"Show Icon", "圖示"},
        {"Show Item Name", "物品名稱"},
        {"Rifles", "步槍"},
        {"SMGs", "衝鋒槍"},
        {"Snipers", "狙擊槍"},
        {"Pistols", "手槍"},
        {"Grenades", "投擲物"},
        {"Utility", "道具"},

        // --- projectile esp ---------------------------------------------
        {"VISUAL ELEMENTS", "顯示元素"},
        {"COLORS", "顏色"},
        {"Enable Projectiles", "啟用投擲物 ESP"},
        {"Display Mode", "顯示模式"},
        {"Indicator", "指示器"},
        {"Text Only", "僅文字"},
        {"Show Text", "顯示文字"},
        {"Effect Timer", "效果計時"},
        {"Effect Timer Ring", "計時圓環"},
        {"Inferno Bounds", "燃燒範圍"},
        {"INDICATOR", "指示器"},
        {"Timer Full", "計時:滿"},
        {"Timer Low", "計時:低"},
        {"Indicator Background", "指示器背景"},
        {"INFERNO GRADIENT", "燃燒漸層"},
        {"Gradient Width", "漸層寬度"},
        {"Gradient Opacity", "漸層亮度"},
        {"HE Grenade", "手榴彈"},
        {"Flashbang", "閃光彈"},
        {"Smoke", "煙霧彈"},
        {"Molotov", "燃燒彈"},
        {"Decoy", "誘餌彈"},

        // --- bomb esp ---------------------------------------------------
        {"STATES", "狀態"},
        {"SAFE ZONE (BAKED)", "安全區"},
        {"Enable Bomb ESP", "啟用炸彈 ESP"},
        {"Show Carrier", "顯示攜帶者"},
        {"Show Planted", "顯示已放置"},
        {"Planted Color", "已放置顏色"},
        {"Defusing Color", "拆彈顏色"},
        {"Panel Background", "面板背景"},
        {"World Timer Ring", "世界計時圓環"},
        {"World Timer", "世界計時器"},
        {"Bomb Info Panel", "炸彈資訊面板"},
        {"Timer Color", "計時器顏色"},
        {"Safe Zone Contour", "安全區輪廓"},
        {"Zone Color", "區域顏色"},
        {"Gradient Bands", "漸層帶"},
        {"Band Step", "漸層帶間距"},

        // --- radar / world ----------------------------------------------
        {"RADAR OVERLAY", "雷達"},
        {"Overlay Enemy Markers", "敵人標記"},
        {"NO FLASH (WIREFRAME)", "無閃光 (線框)"},
        {"Enable Visual No Flash", "啟用視覺無閃光"},
        {"Render Distance", "渲染距離"},
        {"Dimming Overlay Color", "變暗顏色"},
        {"Wireframe Color", "線框顏色"},
        {"NO SMOKE (WIREFRAME)", "無煙霧 (線框)"},
        {"Enable Visual No Smoke", "啟用視覺無煙霧"},
        {"Smoke Wireframe Color", "煙霧線框顏色"},

        // --- crosshair --------------------------------------------------
        {"CROSSHAIR SETTINGS", "準心設定"},
        {"Enable Crosshair", "啟用準心"},
        {"Weapon Sync", "武器同步"},
        {"Draw Dot", "中心點"},
        {"Draw Lines", "準星線"},
        {"T-Style", "T 型"},
        {"Length", "長度"},
        {"Gap", "間距"},
        {"Thickness", "粗細"},
        {"Draw Outline", "描邊"},
        {"Primary Color", "主色"},
        {"Penetration Indicator", "穿透指示器"},
        {"Can Penetrate", "可穿透"},
        {"Cannot Penetrate", "不可穿透"},

        // --- misc tabs --------------------------------------------------
        {"General", "一般"},
        {"Movement", "移動"},
        {"Effects", "效果"},
        {"Overlay", "覆蓋層"},
        {"Lua API", "Lua API"},
        {"Configs", "設定檔"},
        {"LUA RUNTIME", "LUA 執行環境"},
        {"SCRIPTS", "腳本"},
        {"Enable Lua API", "啟用 Lua API"},
        {"Script Directory", "腳本目錄"},
        {"Open Folder", "開啟資料夾"},
        {"Load Lua Script", "載入 Lua 腳本"},
        {"Copy link", "複製連結"},
        {"Copy Path", "複製路徑"},
        {"Discover Scripts", "重新整理清單"},
        {"Refresh", "重新整理"},
        {"No Lua scripts found", "未找到 Lua 腳本"},
        {"Copy scripts into the Lua directory", "請將腳本複製到 Lua 目錄"},
        {"Autoload", "自動載入"},
        {"Hot Reload", "熱重載"},
        {"Status", "狀態"},
        {"Runtime", "執行狀態"},
        {"Last Error", "最後錯誤"},
        {"Reload Script", "重新載入腳本"},
        {"Reload", "重新載入"},

        // --- misc: general ----------------------------------------------
        {"AUTOMATION", "自動化"},
        {"Auto Accept Match", "自動接受對戰"},
        {"GRENADES", "投擲物"},
        {"LINEUP HELPER", "道具點位助手"},
        {"GRENADE ASSIST", "投擲物輔助"},
        {"TRAJECTORY", "彈道"},
        {"Lineup Helper", "道具點位"},
        {"Draw Distance", "繪製距離"},
        {"Marker Distance", "標記距離"},
        {"Stand Radius", "站位半徑"},
        {"Release Radius", "鬆鍵半徑"},
        {"Height Tolerance", "高度容差"},
        {"Show Throw Type", "顯示投擲方式"},
        {"Show Distance", "顯示距離"},
        {"Plaque Background", "提示牌背景"},
        {"Plaque Text", "提示牌文字"},
        {"Plaque Accent", "提示牌強調色"},
        {"Stand Marker", "站位標記"},
        {"Stand Marker Active", "站位標記 (啟用)"},
        {"Aim Marker", "瞄準標記"},
        {"Lineup Aim Assist", "點位瞄準輔助"},
        {"Aim Key", "瞄準鍵"},
        {"Auto Release", "自動投擲"},
        {"Lock Threshold", "鎖定閾值"},
        {"Settle Time", "穩定時間"},
        {"Enemy Aim Assist", "敵人投擲輔助"},
        {"Activation Key", "啟動鍵"},
        {"Target FOV", "目標 FOV"},
        {"Trajectory Preview", "彈道預覽"},
        {"Local Prediction Only", "僅本地投擲"},
        {"Line Style", "線條樣式"},
        {"Line Color", "線條顏色"},
        {"Line Thickness", "線條粗細"},
        {"Bloom", "光暈"},
        {"Bloom Color", "光暈顏色"},
        {"Bloom Radius", "光暈半徑"},
        {"Bounce Points", "反彈點"},
        {"End Point", "終點"},
        {"Point Color", "點顏色"},
        {"Point Size", "點大小"},
        {"ENGINE", "引擎"},
        {"FPS Limiter", "幀率限制"},
        {"Maximum FPS", "最大幀率"},
        {"INTERFACE", "介面"},
        {"LANGUAGE", "語言"},
        {"Language", "語言"},
        {"DPI Scale", "DPI 縮放"},

        // --- misc: movement ---------------------------------------------
        {"BUNNY HOP", "連跳"},
        {"EDGE JUMP", "邊緣跳"},
        {"Enable Bunny Hop", "啟用連跳"},
        {"Enable Edge Jump", "啟用邊緣跳"},

        // --- misc: effects ----------------------------------------------
        {"BULLET TRACERS", "彈道曳光"},
        {"Enable Bullet Tracers", "啟用曳光彈"},
        {"Tracer Color", "曳光顏色"},
        {"Fade Duration", "淡出時長"},
        {"Max Tracers", "最大曳光數"},
        {"Bloom Effect", "光暈效果"},
        {"Draw Impact Cubes", "命中方塊"},
        {"Draw Trajectory Line", "彈道線"},
        {"Cube Size", "方塊大小"},
        {"Fade Near", "近距淡出"},
        {"Fade Far", "遠距淡出"},

        // --- misc: overlay ----------------------------------------------
        {"CAPTURE", "擷取"},
        {"OBS Bypass", "繞過 OBS"},
        {"WATERMARK", "浮水印"},
        {"Show Watermark", "顯示浮水印"},
        {"Show Ping", "顯示延遲"},
        {"Show Loss", "顯示丟包"},
        {"Show CPU Load", "顯示 CPU 佔用"},
        {"Show FPS", "顯示 FPS"},

        {"SPECTATOR LIST", "觀戰列表"},
        {"Show Spectators", "顯示觀戰者"},
        {"EVENT LOG", "事件日誌"},
        {"Event Log", "事件日誌"},
        {"Show Event Log", "顯示事件日誌"},
        {"Maximum Entries", "最大條目數"},
        {"Events", "事件"},
        {"Shots", "開槍"},
        {"Hits", "命中"},
        {"Kills", "擊殺"},
        {"Misses", "落空"},
        {"Blocked", "阻擋"},
        {"Info", "資訊"},
        {"ACTIVE BINDS", "啟用的按鍵"},
        {"Active Binds", "啟用的按鍵"},
        {"Show Active Binds", "顯示啟用按鍵"},
        {"Always On Binds", "常開按鍵"},
        {"Hold Binds", "按住按鍵"},
        {"Toggle Binds", "切換按鍵"},
        {"BOMB PANEL", "炸彈面板"},
        {"Show Bomb Info", "顯示炸彈資訊"},
        {"No active entries", "暫無活動條目"},
        {"Spectators", "觀戰者"},

        {"Steam Avatars", "Steam 頭像"},
        {"  fixed camera", "  固定鏡頭"},
        {"  first person", "  第一人稱"},
        {"  third person", "  第三人稱"},
        {"  free camera", "  自由鏡頭"},

        // --- misc: configs ----------------------------------------------
        {"CFG FILE", "設定檔"},
        {"File Name", "檔案名稱"},
        {"Export Named CFG", "儲存"},
        {"Save As...", "另存為..."},
        {"Open CFG", "載入"},
        {"Browse...", "瀏覽..."},

        // --- esp editor -------------------------------------------------
        {"ESP EDITOR", "ESP 編輯器"},
        {"PREVIEW UNAVAILABLE", "預覽不可用"},

        {"Manual lineup", "手動點位"},
        {"Hold {}, release", "按住 {}, 鬆開"},
        {"Hold {}, {}, release", "按住 {}, {}, 鬆開"},
        {"LMB", "左鍵"},
        {"RMB", "右鍵"},
        {"LMB+RMB", "左鍵+右鍵"},
        {"m", "公尺"},

        {"Jump+Throw", "跳投"},
        {"W+Jump+Throw", "W+跳投"},
        {"Run+Jump+Throw", "跑動跳投"},
        {"Walk+Jump+Throw", "行走跳投"},
        {"Crouch+Jump+Throw", "蹲跳投"},
        {"Crouch+W+Jump+Throw", "蹲+W+跳投"},
        {"Crouch+Run+Jump+Throw", "蹲+跑動跳投"},
        {"WJump+Throw", "W+跳投"},
        {"Jump+Throw LRMB", "跳投 左鍵+右鍵"},
        {"Jump+Throw RMB", "跳投 右鍵"},
        {"W+Jump+Throw LRMB", "W+跳投 左鍵+右鍵"},
        {"W+Jump+Throw RMB", "W+跳投 右鍵"},
        {"Run+Jump+Trhow", "跑動跳投"},
        {"W+Jump+Throwv", "W+跳投"},
        {"Throw", "投擲"},
        {"Throw LRMB", "投擲 左鍵+右鍵"},
        {"Throw RMB", "投擲 右鍵"},
        {"Throw (crouch)", "下蹲投擲"},
        {"Throw (break glass)", "投擲 (碎玻璃)"},
        {"Run+Thorw", "跑動投擲"},
        {"Run+Throw", "跑動投擲"},
        {"Crouch+Run+Throw", "蹲+跑動投擲"},
        {"Go Left then W+Jump+Throw", "先左移, 再 W+跳投"},
        {"Go Right then W+Jump+Throw", "先右移, 再 W+跳投"},
        {"Complex, move left and back and jumpthrow while running",
         "複雜: 左移後退, 跑動跳投"},
        {"Insta Window (no autothrow)", "瞬時窗口 (無自動投擲)"},
        {"Insta Long Door (no autothrow)", "瞬時長門 (無自動投擲)"},

        // Fallback tokens, used for any combination not spelled out above.
        {"Jump", "跳躍"},
        {"Crouch", "下蹲"},
        {"Run", "跑動"},
        {"Walk", "行走"},
        {"Step", "步"},
        {"Forward", "前進"},
        // The source table spells these wrong; kept verbatim as keys.
        {"Trhow", "投擲"},
        {"Thorw", "投擲"},
        {"Throwv", "投擲"},

        // --- feature descriptions (tooltips) -----------------------------
        {"Adds a configurable delay and randomization before and after each trigger shot.",
         "在每次扳機開火前後加入可調的延遲與隨機化。"},
        {"Fires ahead of moving targets by simulating where they will be when the bullet lands.",
         "透過模擬子彈命中時目標的位置, 提前向移動目標開火。"},
        {"Turns the combat feature on and controls whether it is always on, held or toggled.",
         "開啟該戰鬥功能, 並控制它為常開、按住或切換觸發。"},
        {"Only fires when a shot can deal at least the configured damage to the target.",
         "只有當這一槍能對目標造成至少設定傷害時才會開火。"},
        {"Limits how far from the crosshair targets can be picked; open for radius modes.",
         "限制準星多遠範圍內的目標會被選取; 開啟查看半徑模式。"},
        {"Blends in human aim traits like reaction delay, overshoot and jitter on top of the aim path.",
         "在瞄準軌跡上疊加人類瞄準特徵, 如反應延遲、過衝與抖動。"},
        {"Adds extra aim points on each hitbox and can scale them per body part.",
         "為每個命中框添加額外瞄準點, 並可按身體部位縮放。"},
        {"Compensates weapon recoil automatically with per-axis strength and human-like variation.",
         "自動補償武器後座力, 可按軸向設定強度並帶有人類化差異。"},
        {"Draws boxes, health, weapons and more for every visible enemy on your screen.",
         "為螢幕上每個可見敵人繪製方框、血量、武器等資訊。"},
        {"Makes enemies appear spotted on radar, visible and audible like legit information.",
         "讓敵人在雷達上顯示被點亮, 並以合法資訊的樣式顯示可見與可聽狀態。"},
        {"Draws the bullet flight path between your shots and their impact points.",
         "繪製從你的開火位置到彈著點的子彈飛行軌跡。"},
        {"Plays a hit confirmation sound and can show floating damage numbers.",
         "播放命中確認音效, 並可顯示浮動傷害數字。"},
        {"Switches the whole interface language; applies immediately and is saved to the config.",
         "切換整個介面語言; 立即生效並儲存到設定。"},
        {"Scales the entire menu up or down without changing in-game rendering.",
         "整體縮放選單大小, 不影響遊戲內渲染。"},
        {"Customizes every menu color: text, panels, popups, accent and borders.",
         "自訂選單的每種顏色: 文字、面板、彈出視窗、強調色與邊框。"},
        {"Caps the overlay frame rate to reduce CPU and GPU usage.",
         "限制懸浮視窗幀率, 降低 CPU 與 GPU 佔用。"},
        {"Guides you through grenade lineups with on-screen stand and aim markers.",
         "透過螢幕上的站位與瞄準標記引導你完成手榴彈點位。"},
        {"Aligns your view to the lineup and can release the grenade automatically.",
         "將視角對齊到點位, 並可自動鬆手投擲。"},
        {"Steers your aim toward enemies while throwing grenades.",
         "投擲手榴彈時將你的瞄準引導向敵人。"},
        {"Draws the predicted grenade flight path, bounces and landing point.",
         "繪製預測的手榴彈飛行軌跡、彈跳點與落點。"},
        {"Automatically jumps the moment you touch the ground while holding the key.",
         "按住按鍵時, 一觸地就自動跳躍。"},
        {"Jumps at the exact edge of a platform for maximum jump distance.",
         "在平台邊緣的精確瞬間起跳, 達到最大跳躍距離。"},
        {"Halts your movement automatically before shots to make them fully accurate.",
         "開火前自動停止移動, 讓每一槍完全精準。"},
        {"Shows a small performance plaque with ping, loss, CPU load and FPS.",
         "顯示一個小型效能銘牌, 包含延遲、丟包、CPU 負載與 FPS。"},
        {"Logs shots, hits, kills and other events in a compact list.",
         "以精簡列表記錄開火、命中、擊殺等事件。"},
        {"Lists every active keybind on screen so you always know what is enabled.",
         "在螢幕上列出所有生效的按鍵綁定, 讓你隨時了解開啟的功能。"},
        {"Tints the inside of the player box with separate colors for visible and occluded states.",
         "為玩家方框內部著色, 可見與被遮擋狀態使用不同顏色。"},
        {"Draws the enemy's current weapon next to their box.",
         "在敵人方框旁顯示其目前武器。"},
        {"Shows a health bar beside the player with a configurable layout.",
         "在玩家旁顯示血條, 佈局可設定。"},
        {"Shows an armor bar beside the player with a configurable layout.",
         "在玩家旁顯示護甲條, 佈局可設定。"},
        {"Displays text flags like money, flash, kit and scoped state.",
         "顯示金錢、被閃、護甲包、開鏡狀態等文字標記。"},
        {"Makes the enemy model emit light through walls with a configurable color and radius.",
         "讓敵人模型透過牆壁發光, 顏色與半徑可設定。"},
        {"Bursts the enemy model into particles when they die.",
         "敵人死亡時將其模型爆散為粒子效果。"},
        {"Points toward enemies that are outside your view so you never lose their position.",
         "指向視野外敵人, 讓你不會丟失其位置。"},
        {"Highlights the enemy's head and body hitboxes through walls.",
         "透視顯示敵人的頭部與身體命中框。"},
        {"Draws a fading ring where footsteps and other sounds happen.",
         "在腳步與其他聲音發生處繪製逐漸消散的圓環。"},
        {"Shows a fading ghost of the enemy model at the spot of each hit.",
         "在每次命中的位置顯示敵人模型逐漸消散的殘影。"},
        {"Material applied to enemies you can currently see.",
         "應用於目前可見敵人的材質。"},
        {"Material applied to enemies hidden behind walls or smoke.",
         "應用於被牆壁或煙霧遮擋的敵人的材質。"},
        {"Highlights dropped weapons and gear on the ground.",
         "高亮地面上的掉落武器與裝備。"},
        {"Labels each dropped item with its weapon name.",
         "為每個掉落物標註武器名稱。"},
        {"Shows live grenades and their timers for both teams.",
         "顯示雙方存活中的手榴彈及其計時。"},
        {"Chooses between a colored icon and a text label for projectiles.",
         "選擇投擲物使用彩色圖示還是文字標籤。"},
        {"Outlines the area burning from a Molotov or Incendiary.",
         "勾畫出燃燒瓶或燃燒彈的燃燒範圍。"},
        {"Marks the planted bomb on the world with its defuse timer.",
         "在場景中標記已安放的炸彈及其拆除計時。"},
        {"Shows a compact panel with the bomb timer and defuse progress.",
         "顯示包含炸彈計時與拆除進度的精簡面板。"},
        {"Outlines how far the bomb blast can still deal damage.",
         "勾畫出炸彈爆炸仍能造成傷害的範圍。"},
        {"Draws enemy positions, health and weapons on the in-game radar.",
         "在遊戲內雷達上繪製敵人位置、血量與武器。"},
        {"Adds an outline to radar text for readability.",
         "為雷達文字加入外框, 提升可讀性。"},
        {"Shows grenade icons on the radar with per-type colors.",
         "在雷達上顯示手榴彈圖示, 按類型著色。"},
        {"Draws predicted grenade flight paths on the radar.",
         "在雷達上繪製預測的手榴彈飛行軌跡。"},
        {"Shows grenade effect zones like smoke and molotov areas on the radar.",
         "在雷達上顯示煙霧、燃燒區等手榴彈效果範圍。"},
        {"Draws a marker at the impact point of each confirmed hit.",
         "在每次確認命中的彈著點繪製標記。"},
        {"Draws a wireframe world while flashed so you keep your orientation.",
         "被閃白時以線框繪製場景, 保持方向感。"},
        {"Draws smoke volumes as wireframes so you can see through them.",
         "將煙霧體積繪製為線框, 讓你能看穿煙霧。"},
        {"Draws the crosshair line segments with adjustable length and gap.",
         "繪製準星線段, 長度與間隙可調。"},
        {"Adds an outline around the crosshair for visibility on any background.",
         "為準星加入外框, 在任何背景下都清晰可見。"},
        {"Colors the crosshair to show whether the wall between you and the target can be penetrated.",
         "為準星著色, 提示你與目標之間的牆壁是否可穿透。"},
    };

    return table;
}

} // namespace

void set(id value)
{
    if (value >= id::en && value < id::count)
    {
        g_current.store(value, std::memory_order_relaxed);
    }
}

id current()
{
    return g_current.load(std::memory_order_relaxed);
}

const char *code(id value)
{
    switch (value)
    {
    case id::ru:
        return "RU";
    case id::zh_cn:
        return "CN";
    case id::zh_tw:
        return "TW";
    default:
        return "EN";
    }
}

const char *tr(const char *english)
{
    if (!english || current() == id::en)
    {
        return english;
    }

    const auto &table = current() == id::ru      ? russian()
                        : current() == id::zh_cn ? simplified_chinese()
                                                 : traditional_chinese();
    const auto it = table.find(std::string_view{english});
    return it == table.end() ? english : it->second;
}

std::string_view tr(std::string_view english)
{
    if (current() == id::en)
    {
        return english;
    }

    const auto &table = current() == id::ru      ? russian()
                        : current() == id::zh_cn ? simplified_chinese()
                                                 : traditional_chinese();
    const auto it = table.find(english);
    return it == table.end() ? english : std::string_view{it->second};
}

} // namespace render::localization
